# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RswMs8NOX4W6K3--vUIlRd1VQ191ZqPp
"""

import pandas as pd
import numpy as np

data=pd.read_csv("/content/ecommerceDataset.csv")

data.head()

data.shape

data.columns

# Renaming the columns for simplicity
data = data.rename(columns={
    'Household': 'Category',  # Rename first column
    'Paper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.': 'Product_Description'
})

# Check the result
print(data.columns)

data.head()

data.Category.value_counts()

data.isnull().sum()

data.dropna(inplace=True)

data.shape

data.Category.value_counts()

"""We can see that Dataset is not balance Clothing And Accessories is half of Household"""

balanced_data = data.groupby('Category', group_keys=False).apply(lambda x: x.sample(n=min(8670, len(x)), random_state=2024))

balanced_data.Category.value_counts()

balanced_data.head()

balanced_data.shape

ok={
    'Books':0,
    'Clothing & Accessories':1,
    'Electronics':2,
    'Household':3,
}

balanced_data['Category']=balanced_data['Category'].map(ok)

balanced_data.head()

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(balanced_data['Product_Description'], balanced_data['Category'], test_size=0.2, random_state=202)

X_train

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

v=CountVectorizer()
X_train_count=v.fit_transform(X_train.values)
X_train_count.toarray()[:2]
model=MultinomialNB()
model.fit(X_train_count,y_train)

x_test_t=v.transform(X_test)

pred=model.predict(x_test_t)

from sklearn.metrics import confusion_matrix,classification_report
classf=classification_report(y_test,pred)
print(classf)

text="Flipkart Asus Laptop with i5 core"
text=v.transform([text])

m=model.predict(text)

m